### ISSUE TITLE
Error -11, -9

### ISSUE THREAD

**Issue by pkim** [master131/BrotliSharpLib#2]
Hi,

I have trouble to decompress my protobuf data within a netcore v2 project. I haven't tested if this problem is related to protobuf encoded data only but when I use the same stream in combination with deflate, everything works fine.

I have tested the default quality (which is 11 as far as I know, and 3). By using the quality level 11 I get a -11 error and with a quality level of 3 I get a -9 error.

Compressing the data seems to work well.

Decompress:
`//using (var decomressor = new BrotliStream(source, CompressionMode.Decompress))
using (var decomressor = new DeflateStream(source, CompressionMode.Decompress))
{
    return Serializer.Deserialize<T>(decomressor);
}`

Compress:

`//using (var compressor= new BrotliStream(destination, CompressionMode.Compress))
using (var compressor = new DeflateStream(destination, CompressionMode.Compress))
{
   //compressor.SetQuality(3);
   Serializer.Serialize(compressor, data);
}`

Sorry for the bad format of the code. I don't know why this is printed that stupid in the preview?!

I have attached the 2 brotli compressed files with quality level 3 and 11.
[files.zip](https://github.com/master131/BrotliSharpLib/files/1503867/files.zip)

**Comment by master131** [comment]
Thanks for those sample files, the bug has now been fixed.
