### ISSUE TITLE
Feature Request: Change default quality level to 1

### ISSUE THREAD

**Issue by speige** [master131/BrotliSharpLib#3]
Since Quality 11 is super-slow (especially in c# version), it seems like it should be opt-in instead of default. Most applications will need to make a trade off of speed vs size. The difference in size between Quality 1 and 11 isn't very much (~ 5%), but the speed difference is astronomical (~ 100x slower for C or 200x slower for c#).

It seems unlikely anyone will want to use quality 11. The majority will probably be best served by quality 1.
It might be good to change the default for people who don't read the documentation thoroughly enough & accidentally slow down their application to a halt.

P.S. This is a great lib. Thank you!

**Comment by master131** [comment]
This has now been implemented in the latest version.
