### ISSUE TITLE
Strong named assembly

### ISSUE THREAD

**Issue by justcoding121** [master131/BrotliSharpLib#7]
Can we release a strongly named nuget package, so that other packages that are strongly named can use this. For now in Titanium Web Proxy someone have published a strongly named version of this library. Not sure if its official.

**Comment by justcoding121** [comment]
CloudVeil.BrotliSharpLib is the nuget package we are currently using which just strongly names this package assembly. I have security concern if its not an official build from this project.

**Comment by master131** [comment]
Done, see PR #6 which adds a strong name key. Newest package has been uploaded to Nuget.
